# Generated by Django 5.1.13 on 2025-11-04 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Critico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio_fundacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('estudio_desarrollo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.FloatField()),
                ('fecha', models.DateField()),
                ('critico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.critico')),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.videojuego')),
            ],
        ),
        migrations.CreateModel(
            name='VideojuegoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.plataforma')),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.videojuego')),
            ],
        ),
        migrations.AddField(
            model_name='videojuego',
            name='plataformas',
            field=models.ManyToManyField(through='juegos.VideojuegoPlataforma', to='juegos.plataforma'),
        ),
    ]
