# Generated by Django 5.1.13 on 2025-11-04 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataforma',
            name='fabricante',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='critico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juegos.critico'),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='puntuacion',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='videojuego',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juegos.videojuego'),
        ),
        migrations.AlterField(
            model_name='critico',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='anio_fundacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='estudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juegos.estudio'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='pais',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='estudio_desarrollo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juegos.estudio'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='plataformas',
            field=models.ManyToManyField(null=True, through='juegos.VideojuegoPlataforma', to='juegos.plataforma'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videojuegoplataforma',
            name='plataforma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juegos.plataforma'),
        ),
        migrations.AlterField(
            model_name='videojuegoplataforma',
            name='videojuego',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juegos.videojuego'),
        ),
    ]
